BamdadCell/Areas/Admin/Controllers/CallController.cs
using System;
using System.Linq;
using System.Web.Mvc;

namespace BamdadCell.Areas.Admin.Controllers
{
    public class CallController : Controller
    {
        Repository.IServives.ICallService _callService;

        public CallController(Repository.IServives.ICallService callservice)
        {
            _callService = callservice;
        }
        // GET: Admin/Call
        public ActionResult Index()
        {
            var callist = _callService.GetAllCalls();

            return View(callist);
        }




        // GET: Users/Edit/5
        public ActionResult Edit(Repository.DTO.AdminCallViewModel call, FormCollection collection)
        {
            var ss = _callService.GetAllCalls().FirstOrDefault(s => s.Id == call.Id);
            return View(ss);
        }

        // POST: Users/Edit/5
        [HttpPost]
        public ActionResult Edit(Repository.DTO.AdminCallViewModel cl)
        {
            try
            {
                // TODO: Add update logic here
                _callService.UpdateCalls(cl);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int id)
        {

            return View();
        }

        // POST: Users/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                _callService.DeleteCall(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BamdadCell/Areas/Admin/Controllers/SmsController.cs
using System;
using System.Linq;
using System.Web.Mvc;

namespace BamdadCell.Areas.Admin.Controllers
{
    public class SmsController : Controller
    {
        public Repository.IServives.ISmsService _smsService;

        public SmsController(Repository.IServives.ISmsService smsService)
        {
            //_userService = new Repository.IServives.IUserService();
            _smsService = smsService;

        }
        // GET: Admin/Sms
        public ActionResult Index()
        {
            var listUsers = _smsService.GetAllSms();

            return View(listUsers);
        }




        // GET: Users/Edit/5
        public ActionResult Edit(Repository.DTO.AdminSmsViewModel sms, FormCollection collection)
        {
            var ss = _smsService.GetAllSms().FirstOrDefault(s => s.Id == sms.Id);
            return View(ss);
        }

        // POST: Users/Edit/5
        [HttpPost]
        public ActionResult Edit(Repository.DTO.AdminSmsViewModel sms)
        {
            try
            {
                // TODO: Add update logic here
                _smsService.UpdateSms(sms);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int id)
        {

            return View();
        }

        // POST: Users/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                _smsService.DeleteSms(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BamdadCell/Controllers/ChargeController.cs
using Repository.DTO;
using System.Web.Mvc;
using Repository.Services;



namespace BamdadCell.Controllers
{
    public class ChargeController : Controller
    {

        public Repository.IServives.IChargeService _chargeservice;
        public Repository.IServives.ISimService _simservice;
        public Repository.IServives.IUserService _userService;
        public Repository.IServives.ISmsService _smsService;


        public ChargeController(Repository.IServives.IChargeService chargesimservices, Repository.IServives.ISimService simservices, Repository.IServives.IUserService userservices, Repository.IServives.ISmsService smsservice)
        {
            _chargeservice = chargesimservices;
            _simservice = simservices;
            _userService = userservices;
            _smsService = smsservice;

        }
        // GET: Charge
        [Authorize]
        public ActionResult BuyCharge()
        {

            int SenderAccountId = _userService.GetUserIdByEmail(User.Identity.Name);

            var sims = _simservice.GetAllSimIdByPersonId(SenderAccountId);

            if (sims.Count > 0)
            {

                var sendersimId = _simservice.GetSimIdByPersonId(SenderAccountId);
                var Credit = _simservice.IsSimCredit(sendersimId);
                ViewBag.ChargeInfo = _chargeservice.ShowCharges();
                if (Credit)
                {
                    ViewBag.SenderNumbers = _simservice.GetSenderNumbers(SenderAccountId);

                    return View();
                }
                else
                {
                    return View("Credit");
                }
            }

            return View("NoSim");

        }

        [HttpPost]
        public ActionResult BuyCharge(ShowChargesVIewModel scvm)
        {
            int SenderAccountId = _userService.GetUserIdByEmail(User.Identity.Name);
            //// Person Id => Sim Id
            ///
            var sendersimId = int.Parse(Request.Form["SenderNumbers"]);

            //  var sendersimId = _simservice.GetSimIdByPersonId(SenderAccountId);

            var Balance = _simservice.GetSimBalance(sendersimId);
            var chargeId = int.Parse(Request.Form["ChargeInfo"]);
            var chargeprice = _chargeservice.GetChargePriceByChargeId(chargeId);
            var newBalance = Balance += chargeprice;


            _smsService.UpdateBalanceById(sendersimId, newBalance);
            _chargeservice.UpdateChargeStatus(chargeId);
            _chargeservice.ChargeSim(sendersimId, chargeId);
            return (Redirect("/"));
        }
    }
}

BamdadCell/Controllers/HomeController.cs
using Repository.DTO;
using System;
using System.Web.Mvc;

namespace BamdadCell.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {


        public Repository.IServives.ISimService _simService;
        public Repository.IServives.IUserService _userService;
        public Repository.IServives.ISmsService _smsService;
        public Repository.IServives.ICallService _callService;


        public HomeController(Repository.IServives.ISimService simService, Repository.IServives.IUserService userService, Repository.IServives.ISmsService smsService, Repository.IServives.ICallService callService)
        {
            _simService = simService;
            _userService = userService;
            _smsService = smsService;
            _callService = callService;
        }
        public ActionResult Index()
        {
            int SenderAccountId = _userService.GetUserIdByEmail(User.Identity.Name);
            //// Person Id => Sim Id
            // var SenderId = _simService.GetSimIdByPersonId(SenderAccountId);

            var allsenderId = _simService.GetAllSimIdByPersonId(SenderAccountId);


            var SmsList = _smsService.ShowUserSmsList(allsenderId);



            return View(SmsList);
        }

        public ActionResult Sms()
        {
            int SenderAccountId = _userService.GetUserIdByEmail(User.Identity.Name);
            var sims = _simService.GetAllSimIdByPersonId(SenderAccountId);
            if (sims.Count > 0)
            {
                ViewBag.SenderNumbers = _simService.GetSenderNumbers(SenderAccountId);
                ViewBag.ReciverNumbers = _simService.GetReciverNumbers(SenderAccountId);
                return View();
            }

            return View("NoSim");


        }
        [HttpPost]
        public ActionResult Sms(SmsViewModel smsvm)
        {

            int SenderAccountId = _userService.GetUserIdByEmail(User.Identity.Name);
            var sims = _simService.GetAllSimIdByPersonId(SenderAccountId);
            if (sims.Count > 0)
            {

                var reciversimId = int.Parse(Request.Form["ReciverNumbers"]);
                var reciversimnumber = _simService.GetSimNumberIdBySimId(reciversimId);
                if (_simService.IsExistSim(reciversimnumber))
                {

                    var SenderId = int.Parse(Request.Form["SenderNumbers"]);
                    var ReciverSimId = int.Parse(Request.Form["ReciverNumbers"]);
                    
                    
                    var Credit = _simService.IsSimCredit(SenderId);
                    var Balance = _simService.GetSimBalance(SenderId);
                    var tarrif = _smsService.GetSmsTariff();

                    if (_simService.IsSimActive(SenderId))
                    {
                        if (Credit)
                        {
                            if (Balance >= 0)
                            {
                                var newBalance = Balance -= tarrif;
                                _smsService.UpdateBalanceById(SenderId, newBalance);
                                _smsService.AddSms(smsvm, SenderId, ReciverSimId);
                            }
                            else
                            {
                                return View("NoBalance");
                            }
                        }
                        else
                        {
                            if (Balance >= -20000)
                            {
                                var reBalance = Balance -= tarrif;
                                _smsService.UpdateBalanceById(SenderId, reBalance);
                                _smsService.AddSms(smsvm, SenderId, ReciverSimId);
                            }
                            else
                            {
                                return View("NoCredit");
                            }
                        }

                    }

                    else
                    {
                        return View("BlockSim");
                    }
                    return Redirect("/");



                }
                else
                {

                    return View();
                }
                return View();
            }
            else
            {
                return View("NoSim");
            }
        }







        public ActionResult ShowCalls()
        {
            int SenderAccountId = _userService.GetUserIdByEmail(User.Identity.Name);

            var sims = _simService.GetAllSimIdByPersonId(SenderAccountId);
            if (sims.Count > 0)
            {


                ViewBag.SenderNumbers = _simService.GetSenderNumbers(SenderAccountId);
                //// Person Id => Sim Id
                var SenderId = _simService.GetSimIdByPersonId(SenderAccountId);

                var allSimId = _simService.GetAllSimIdByPersonId(SenderAccountId);

                var callList = _callService.ShowUserCallList(allSimId);
                return View(callList);

            }

            return View("NoSim");

        }

        public ActionResult Call()
        {
            int SenderAccountId = _userService.GetUserIdByEmail(User.Identity.Name);

            var sims = _simService.GetAllSimIdByPersonId(SenderAccountId);
            if (sims.Count > 0)
            {


                ViewBag.SenderNumbers = _simService.GetSenderNumbers(SenderAccountId);
                ViewBag.ReciverNumbers = _simService.GetReciverNumbers(SenderAccountId);


                return View();
            }

            return View("NoSim");



        }

        [HttpPost]
        public ActionResult Call(CallsViewModel callvm)
        {
            // var ReciverrId = int.Parse(Request.Form["ReciverNumbers"]);
            var reciversimId = int.Parse(Request.Form["ReciverNumbers"]);
            var reciversimnumber = _simService.GetSimNumberIdBySimId(reciversimId);
            if (_simService.IsExistSim(reciversimnumber))
            {

                int SenderAccountId = _userService.GetUserIdByEmail(User.Identity.Name);
                //// Person Id => Sim Id
                //var SenderId = _simService.GetSimIdByPersonId(SenderAccountId);
                var SenderId = int.Parse(Request.Form["SenderNumbers"]);



                var ReciverSimId = int.Parse(Request.Form["ReciverNumbers"]);
                var Duration = callvm.CallDuration;

                string nowtime = DateTime.Now.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss");
                var time = DateTime.Parse(nowtime);

                var Credit = _simService.IsSimCredit(SenderId);
                var Balance = _simService.GetSimBalance(SenderId);
                var tarrif = _callService.GetCallTariff();
                if (_simService.IsSimActive(SenderId))
                {
                    if (Credit)
                    {
                        if (Balance >= 0)
                        {
                            var newBalance = Balance -= (tarrif * Duration);
                            _callService.UpdateBalanceById(SenderId, newBalance);
                            _callService.AddCall(callvm, SenderId, ReciverSimId);

                        }
                        else
                        {
                            return View("NoBalance");
                        }
                    }
                    else
                    {
                        if (Balance >= -20000)
                        {
                            var reBalance = Balance -= (tarrif * Duration);


                            _smsService.UpdateBalanceById(SenderId, reBalance);
                            _callService.AddCall(callvm, SenderId, ReciverSimId);


                        }
                        else
                        {
                            return View("NoCredit");
                        }
                    }

                }

                else
                {
                    return View("BlockSim");
                }
                return Redirect("/Home/ShowCalls");



            }
            else
            {
                ModelState.AddModelError("Reciver", "Number Is Not Exist");

                return View();
            }
            return View();
        }



    }
}

BamdadCell/Controllers/ReceiptController.cs
using Repository.DTO;
using System;
using System.Globalization;
using System.Web.Mvc;

namespace BamdadCell.Controllers
{
    public class ReceiptController : Controller
    {

        public Repository.IServives.IUserService _userService;
        public Repository.IServives.IReceiptService _receiptService;
        public Repository.IServives.ISimService _simservice;
        public Repository.IServives.ISmsService _smsService;


        public ReceiptController(Repository.IServives.IReceiptService receiptservices, Repository.IServives.IUserService userservices, Repository.IServives.ISimService simservices, Repository.IServives.ISmsService smsServices)
        {
            _receiptService = receiptservices;
            _userService = userservices;
            _simservice = simservices;
            _smsService = smsServices;
        }
        // GET: Receipt
        public ActionResult Payment()
        {
            int SenderAccountId = _userService.GetUserIdByEmail(User.Identity.Name);

            var sims = _simservice.GetAllSimIdByPersonId(SenderAccountId);

            if (sims.Count > 0)
            {

                var allsender = _simservice.GetAllSimIdByPersonId(SenderAccountId);
                var Credit = _simservice.IsAllSimCredit(allsender);

                if (!Credit)
                {
                    var receiptlist = _receiptService.GetReceipt(SenderAccountId, allsender);
                    return View(receiptlist);
                }
                else
                {
                    return View("Receipttype");
                }
            }
            return View("NoSim");

        }

        [HttpPost]
        public ActionResult Payment(ShowReceiptViewModel srvm)
        {
            var simId = _userService.GetSimIdByNumber(srvm.SimCart);

            var jtime = Extentions.TimeConvertor.ToShamsi();
            var ptime = DateTime.ParseExact(jtime, "yyyy/MM/dd HH:mm:ss", CultureInfo.GetCultureInfo("fa-IR"));
            _smsService.UpdateBalanceById(simId, 0);
            _receiptService.PayReceipt(srvm.Price, simId, ptime);
            return (Redirect("/"));
        }

    }

}

BamdadCell/Views/Home/BlockSim.cshtml
<link href="~/Content/BlockSim.css" />
<section class="page_404">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 ">
                <div class="col-sm-10 col-sm-offset-1  text-center">
                    <div class="four_zero_four_bg">
                        <h1 class="text-center ">آخ!</h1>


                    </div>

                    <div class="contant_box_404">
                        <h3 class="h2">
                            به نظر میرسد اکانت شما مسدود شده باشد
                        </h3>

                        <p>برای اطلاعات بیشتر با پشتیبانی تماس بگیرید</p>

                        <a href="/" class="link_404">Go to Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

BamdadCell/Views/Home/Call.cshtml
@model Repository.DTO.CallsViewModel

@{
    ViewBag.Title = "Call";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>تماس</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CallDuration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CallDuration, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CallDuration, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Sender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SenderNumbers", null, htmlAttributes: new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.Sender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Reciver, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
             @Html.DropDownList("ReciverNumbers", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Reciver, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="برقراری تماس" class="btn btn-default" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BamdadCell/Views/Home/Index.cshtml
@model IEnumerable<Repository.DTO.SmsViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>پیام ها</h2>

<p>
    @Html.ActionLink("پیام جدید", "Sms")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reciver)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Reciver)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
      
    </tr>
}

</table>

BamdadCell/Views/Home/NoBalance.cshtml
@{
    ViewBag.Title = "NoBalance";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>اعتبار شما تمام شده است</h2>

<button type="button" class="btn btn-warning">@Html.ActionLink("خرید شارژ", "BuyCharge", "Charge")</button>

BamdadCell/Views/Home/NoCredit.cshtml
@{
    ViewBag.Title = "NoCredit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>مشتری گرامی بدهی شما به علت بدهی سیم کارت شما قطع میباشد</h2>


<button type="button" class="btn btn-warning">@Html.ActionLink("پرداخت بدهی", "Payment", "Receipt")</button>

BamdadCell/Views/Home/ShowCalls.cshtml
@model IEnumerable<Repository.DTO.CallsViewModel>

@{
    ViewBag.Title = "ShowCalls";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>تماس ها</h2>

<p>
    @Html.ActionLink("تماس جدید", "Call")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CallDuration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reciver)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CallDuration) دقیقه
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Reciver)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
   
    </tr>
}

</table>

BamdadCell/Views/Home/Sms.cshtml
@model Repository.DTO.SmsViewModel

@{
    ViewBag.Title = "Sms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>پیام جدید</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SenderNumbers", null, htmlAttributes: new { @class = "form-control" })


            @Html.ValidationMessageFor(model => model.Sender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Reciver, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ReciverNumbers", null, htmlAttributes: new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.Reciver, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="ارسال" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}